name    'dalen-puppetls'
version '0.2.0'
author 'Erik Dalén <erik.gustav.dalen@gmail.com>'
license 'Apache Licence v2'
summary 'Puppet face to list file resources'
project_page 'https://github.com/dalen/puppetls'
